function myFunction(){
    const message =
    [' "I would rather spend one moment holding you than a lifetime knowing I never could." — Unknown',
    ' “But you have slipped under my skin, invaded my blood and seized my heart.” — Maria V. Snyder',
    ' “I never loved you any more than I do, right this second. And I will never love you any less than I do, right this second.”— Kami Garcia, Margaret Stohl',
    ' “I love you and I don’t want to lose you. Because my life has been better since the day I found out.” – Unknown',
    ' “You have bewitched me, body and soul, and I love, I love, I love you. I never wish to be parted from you from this day on.” – Pride and Prejudice',
    ' I do know some things. I know I love you. I know you love me.” – Game of Thrones',
    ' “And in her smile I see something more beautiful than the stars.”— Across the Universe',
    ' "As he read, I fell in love the way you fall asleep: slowly, and then all at once." ― John Green',
    ' “I want you. All of you. Your flaws. Your mistakes. Your imperfections. I want you, and only you.” – John Legend',
    ' “I’ve never had a moment’s doubt. I love you. I believe in you completely. You are my dearest one. My reason for life.” – Ian McEwan',
    ' "When I saw you I fell in love, and you smiled because you knew." ― Arrigo Boito',
    ' "When I saw you I fell in love, and you smiled because you knew." ― Arrigo Boito',
    ' “So, I love you because the entire universe conspired to help me find you." ― Paulo Coehlo',
    ' “I swear I couldn’t love you more than I do right now, and yet I know I will tomorrow.” – Leo Christopher',
    ' “If I had a flower for every time I thought of you, I could walk in my garden forever.” – Unknown',
    ' “I don’t care how hard being together is, nothing is worse than being apart.” — Josephine Angelini',
    ' “In a sea of people, my eyes will always be searching for you.” – Unknown',
    ' “Sometimes, I knock on the doors of your heart, just to make sure I still live there.” – Unknown',
    ' “No matter what has happened. No matter what you’ve done. No matter what you will do. I will always love you. I swear it.” — C.J. Redwine',
    ' “I am catastrophically in love with you.”— Cassandra Clare',
    ' “And I’ve realized that the Beatles got it wrong. Love isn’t all we need—love is all there is.”— Morgan Matson',
    ' "Promise me you will never forget me, because if I thought you would, Id never leave." ― A.A. Milne',
    ' “Your hand touching mine. This is how galaxies collide.” ― Sanober Khan',
    ' "Love is like a virus. It can happen to anybody at any time." – Maya Angelou',
    ' “I wish I knew how to quit you.” – Brokeback Mountain',
    ' “Loved you yesterday, love you still, always have, always will.” – Elaine Davis',
    ' "I need you like a heart needs a beat." — One Republic',
    ' "When I look into your eyes, I know I have found the mirror of my soul." — Joey W. Hill',
    ' “Morning without you is a dwindled dawn.” — Emily Dickinson',
    ' "It was love at first sight, at last sight, at ever and ever sight." ― Vladimir Nabokov',
    ' “Your absence has not taught me how to be alone; it has merely shown me that when together we cast a single shadow on the wall.” — Doug Fetherling',
    ' “Your love shines in my heart as the sun that shines upon the earth.” – Eleanor Di Guillo',
    ' “I would rather share one lifetime with you than face all the ages of this world alone.” – J.R.R Tolkien',
    ' “Each day I love you more, today more than yesterday and less than tomorrow.” – Rosemonde Gerard',
    ' “I am in you and you in me, mutual in divine love.” – William Blake',
    ' “Love is being stupid together.” – Paul Valéry',
    ' “My heart is and always will be yours.” – Jane Austen',
    ' “If I had to choose between breathing and loving you I would use my last breath to tell you I love you.” – DeAnna Anderson',
    ' “You had me at hello.” – Jerry Maguire',
    ' “Absence is to love as wind is to fire; it extinguishes the small and kindles the great.” — Roger de Bussy-Rabutin',
    ' “If I tell you I love you, can I keep you forever?” – Casper',
    ' “For it was not into my ear you whispered, but into my heart. It was not my lips you kissed, but my soul.” – Judy Garland',
    ' “No matter where I went, I always knew my way back to you. You are my compass star.” — Diana Peterfreund', 
    ' “I love you and I like you” – Parks & Recreation',
    ' “The scariest thing about distance is you don’t know if they’ll miss you or forget about you.”— Nicholas Sparks',
    ' “You know you’re in love when you can’t fall asleep because reality is finally better than your dreams.” – Dr. Seuss',
    ' “And I don’t mind if we take our time ‘cause I’m all yours if you’re all mine.” – Defeater',
    ' “Love is missing someone when you’re apart, but somehow feeling warm inside because you’re close in the heart.” — Kay Knudsen',
    ' Love makes no sense if it is not to the right person. I feel very lucky to be with you!',
    ' You are the owner of my heart, my feelings, my soul and my body. I completely belong to you, baby. I love you. Always.',
    ' Your image is always in my mind, I can always hear my heart whispering your name and I can always see your face when I close my face, how beautiful you are. I love you.',
    ' You can keep my heart but bring me back to life with your kisses. Miss you!',
    ' I absolutely adore you. Just FYI.',
    ' Sweetheart, everything is meaningless without you, you are part of me. Even When we are apart.',
    ' You make me the happiest person on Earth.',
    ' I admire you, I care for you, I love you, I respect you and I trust you. Unconditionally.',
    ' The only thing I need in life is to see you smile; you are the queen of my heart. I love you.',
    ' I wish you two things: everything and nothing. Everything that makes you happy and nothing that makes you suffer. I love you!',
    ' I wish you two things: everything and nothing. Everything that makes you happy and nothing that makes you suffer. I love you!',
    ' You are my dream come true, I will treasure and love you all the days of my life.',
    ' I wish I could send you a kiss through the phone, I could do it every second.',
    ' You make my heart melt!',
    ' You are on my mind every second of every day!',
    ' Counting down the seconds until I get to see you again!',
    ' Just a note to remind you I’m thinking about you.',
    'Just a note to remind you I’m thinking about you.',
    ' I love you to the moon and back.',
    ' I love you 3000',
    ' I did not think it was even possible to love someone as much as I love you.',
    ' You make every day better, which is one of the million reasons I love you.',
    ' "Love is an irresistible desire to be irresistibly desired." — Robert Frost',
    ' "Love is the hardest habit to break and the most difficult to satisfy." — Drew Barrymore',
    ' "Love is the hardest habit to break and the most difficult to satisfy." — Drew Barrymore',
    ' “At the touch of love everyone becomes a poet.” — Plato',
    ' “The only thing we never get enough of is love; and the only thing we never give enough of is love.” — Henry Miller',
    ' I love you,with the kind of love that’s more than love.',
    ' "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage." — Lau Tzu',
    ' "Some love stories are not epic novels. Some are short stories. But that does not make them any less filled with love." — Carrie Bradshaw',
    ' "Who, being loved, is poor? — Oscar Wilde',
    ' "Passion is momentary; love is enduring." —  John Wooden',
    ' "Do I love you? My god, if your love were a grain of sand, mine would be a universe of beaches." — William Goldman',
    ' "To love is nothing to be loved is something..to love and be loved is everything." — Bill Russel',
    ' “If I know what love is, it is because of you.”— Herman Hesse',
    ' "The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space." — Marilyn Monroe',
    '  Hold my hand, hold my heart, and hold me forever. I love you.',
    ' "You have bewitched me body and soul, and I love, I love, I love you." — Pride and Prejudice',
    ' "The sea hath its pearls, the heaven hath its stars, but my heart, my heart has its love." — Henry Wadsworth Longfellow',
    ' "Love never claims, it ever gives. Love ever suffers, never resents, never revenges itself." — Mahatma Gandhi',
    '  I am so in love with you that sometimes I still pinch myself to make sure it is not a dream.',
    ' Every atom, molecule, and cell of me loves you.',
    ' Our love is a promise; our love is a souvenir, once given never forgotten, never let it disappear.',
    ' To the moon and back, I love you.',
    ' "Soul meets soul on lovers lips." - Percy Bysshe Shelley',
    ' "In all the world, there is no heart for me like yours." - Maya Angelou',
    ' "Love is like the wind, you can not see it but you can feel it." - Nicholas Sparks',
    ' "Love is like the wind, you can not see it but you can feel it." - Nicholas Sparks',
    ' "You are my today and all of my tomorrows." - Leo Christopher',
    ' "If I had a flower for every time I thought of you, I could walk through my garden forever." - Alfred Tennyson',
    ' "You are the greatest risk I have ever taken. And the greatest reward." - Sylvia Day',
    ' "True love stories never have endings." - Richard Bach',
    ' All, everything that I understand, I only understand because I love." - Leo Tolstoy',
    ];
    
    const randomIndex =  Math.ceil(Math.random()*message.length);
    document.getElementById('messages').innerHTML = message[randomIndex];
    }